In [1]:
import pandas as pd 
import numpy as np 
from LoadDataset import LoadDataset

In [2]:
#load the dataset
ada_path = "H:\ADAUSDT-trades-2021-01.zip"
ADA = LoadDataset(ada_path)
ADA

,id,price,qty,quoteQty,isBuyerMaker,isBestMatch
time,,,,,,
2021-01-01 00:00:00.041000+00:00,50776846,0.18134,572.3,103.780882,True,True
2021-01-01 00:00:00.592000+00:00,50776847,0.18135,263.4,47.767590,True,True
2021-01-01 00:00:01.265000+00:00,50776848,0.18141,542.4,98.396784,True,True
2021-01-01 00:00:02.051000+00:00,50776849,0.18136,263.5,47.788360,True,True
2021-01-01 00:00:02.051000+00:00,50776850,0.18136,476.2,86.363632,True,True
...,...,...,...,...,...,...
2021-01-31 23:59:58.054000+00:00,63308022,0.34471,107.9,37.194209,True,True
2021-01-31 23:59:59.896000+00:00,63308023,0.34475,82.2,28.338450,True,True
2021-01-31 23:59:59.896000+00:00,63308024,0.34475,713.9,246.117025,True,True
2021-01-31 23:59:59.914000+00:00,63308025,0.34474,4153.0,1431.705220,True,True
2021-01-31 23:59:59.925000+00:00,63308026,0.34475,62.0,21.374500,True,True